services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "authdb"
      POSTGRES_USER: "riss"
      POSTGRES_PASSWORD: "123"
    ports:
      - "9001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "123@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "8080:80"
    depends_on:
      - postgres

  redis:
    image: redis:latest
    environment: 
      REDIS_PASSWORD: 123
      REDIS_USER: riss
      REDIS_USER_PASSWORD: 123
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    environment:
      SWAGGER_JSON: /swagger/auth.swagger.json
    ports:
      - "8082:8080"
    volumes:
      - ../docs/swagger:/swagger
volumes:
  postgres_data:
  redisdata: